# Use Node.js as the base image
FROM node:20 AS base

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy app source code
COPY . .

# Expose development port
EXPOSE 4200

# Set up live-reload for Angular development server
CMD ["yarn", "dev"]
